version: '3.1'

services:
  eserver:
    build: eureka-server
    hostname: eserver
    environment:
      - SPRING_APPLICATION_NAME=eserver
      - EUREKA_NAME=eserver
      - EUREKA_PORT=8761
    container_name: eureka-server-cont
    tty: true
    ports:
      - "8761:8761"
    networks:
      services-network-01:
        aliases:
          - eserver

  eclient:
    build: catalog-server
    hostname: eclient
    container_name: catalog-server-cont
    tty: true
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=eclient
      - EUREKA_NAME=eserver
      - EUREKA_PORT=8761
      - DB_HOST=catalog-db # тут надо указывать имя контейнера,
      #так как база развернута в отдельном контейнере,
      #а localhost - посути это обращение внутрь себя
      - DB_PORT=5432
      - DB_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

    networks:
      services-network-01:
        aliases:
          - eclient
    depends_on:
      - eserver
      - test

  test:
    image: postgres:14-alpine
    container_name: catalog-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      services-network-01:
        aliases:
          - test

  eclient-two:
    build: user-server
    hostname: eclient-two
    environment:
      - SPRING_APPLICATION_NAME=eclient-two
      - API-GATE_PORT=8765
      - API-GATE_HOST=api-gateway-cont
      - EUREKA_NAME=eserver
      - EUREKA_PORT=8761
    container_name: user-server-cont
    tty: true
    ports:
      - "8081:8081"
    networks:
      services-network-01:
        aliases:
          - eclient-two
    depends_on:
      - eserver

  api-gateway:
    build: api-gateway
    hostname: api-gateway
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_NAME=eserver
      - EUREKA_PORT=8761
    container_name: api-gateway-cont
    tty: true
    ports:
      - "8765:8765"
      - "80:8765"
    networks:
      services-network-01:
        aliases:
          - api-gateway
    depends_on:
      - eserver

networks:
  services-network-01:
    name: services-network-01
    driver: bridge