version: '3.8'

services:
  eclient:
    build: catalog-server
    container_name: catalog-app
    hostname: eclient
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - eserver
      - db
    environment:
      - SPRING_APPLICATION_NAME=eclient
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      services-network-01:
        aliases:
          - eclient


  test:
    image: postgres:14-alpine
    container_name: catalog-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data:/var/lib/postgresql/data


